server:
  port: 4004

auth:
  service:
    url: http://localhost:8081

spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/authentication/**, /api/user-credentials/**
          filters:
            - StripPrefix=1

        - id: user-service-route
          uri: http://localhost:8082
          predicates:
            - Path=/api/users-management/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: product-service-route
          uri: http://localhost:8083
          predicates:
            - Path=/api/products-management/**, /api/retailers/**, /api/suppliers/**, /api/products/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: order-service-route
          uri: http://localhost:8084
          predicates:
            - Path=/api/cart/**, /api/order-placement/**, /api/orders/**, /api/order-cancellation/**, /api/orderItem/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # Dedicated route for Stripe webhooks - no authentication required
        - id: stripe-webhook-route
          uri: http://localhost:8085
          predicates:
            - Path=/api/stripe/webhook/**
          filters:
            - StripPrefix=1
            # No JWT validation filter for this route

        # Regular payment service route for authenticated endpoints
        - id: payment-service-route
          uri: http://localhost:8085
          predicates:
            - Path=/api/payments/**, /api/check-out/**
          filters:
            - StripPrefix=1
            - JwtValidation


        