server:
  port: 4004

auth:
  service:
    url: http://auth-service:8085

spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://auth-service:8085
          predicates:
            - Path=/api/authentication/**, /api/user-credentials/**
          filters:
            - StripPrefix=1

        - id: product-service-route
          uri: http://product-service:8080
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1
            - JwtValidation