server:
  port: 4004

auth:
  service:
    url: http://auth-service:8081

spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://auth-service:8081
          predicates:
            - Path=/api/authentication/**, /api/user-credentials/**
          filters:
            - StripPrefix=1

        - id: user-service-route
          uri: http://user-service:8082
          predicates:
            - Path=/api/users-management/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: product-service-route
          uri: http://product-service:8083
          predicates:
            - Path=/api/products-management/**, /api/retailers/**, /api/suppliers/**, /api/products/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: order-service-route
          uri: http://order-service:8084
          predicates:
            - Path=/api/cart/**, /api/order-placement/**, /api/orders/**, /api/order-cancellation/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: payment-service-route
          uri: http://payment-service:8085
          predicates:
            - Path=/api/payments/**, /api/check-out/**, /api/stripe/**
          filters:
            - StripPrefix=1
            - JwtValidation=excludePaths=/api/stripe/**


        